version: '3.8'

services:
  web:
    build: .
    command: ["gunicorn", "--bind", "0.0.0.0:8000", "Core.wsgi:application"]
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    networks:
      - app_network

volumes:
  sqlite_data:

networks:
  app_network:
    driver: bridge
